# Generated by Django 3.2.7 on 2021-09-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('address', models.CharField(max_length=200, verbose_name='Место жительства')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.employee')),
            ],
        ),
    ]
